kind: StorageClass # 创建一个存储类
apiVersion: storage.k8s.io/v1
metadata:
  name: mycsi-sc # 指定存储类名称
provisioner: mycsi.jtthink.com  # 指定 CSI 驱动名称
---
apiVersion: v1
kind: PersistentVolumeClaim # 创建一个 PVC
metadata:
  name: mycsi-pvc
spec:
  accessModes: # 访问模式
    - ReadWriteOnce # 单节点读写
  resources:
    requests:
      storage: 2Gi # 存储大小
  storageClassName: mycsi-sc # 指定存储类
---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      app: mycsi-nginx
  template:
    metadata:
      labels:
        app: mycsi-nginx
    spec:
      containers:
        - name: mycsi-nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: mycsi-pvc
              mountPath: /usr/share/nginx/html
      volumes:
        - name: mycsi-pvc
          persistentVolumeClaim:
            claimName: mycsi-pvc

